# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d50a44bac3cf3bdacebef335b37f7a21235c5bc3f06da98867f5c2c633280f0a60dfc74f67c984d837bb8d095874a413be29a6df1aaac7bf8245d0e7a253f5a5

test:
  secret_key_base: bb0b6e046f5d9a05bfea897982e56d48e867e57287936c79e39db10724fffb51cd95bddab54813fe906cbcc29c9caf0112785addaec1785e68394f1b1f95f75a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
